#!/usr/bin/env python
# The MIT License (MIT)
#
# Copyright (c) 2016 Anshul Joshi anshuljoshi.cse@gmail.com
# license: GNU GENERAL PUBLIC LICENSE <http://www.gnu.org/licenses/gpl-3.0.html>
#
# Anshul Joshi anshuljoshi.github.io


import sys, os
todofile = os.path.expanduser("~/.todo")

def addtotodo(task):
    alltasks = []
    try:
        alltasks = open(todofile, "r").readlines()
    except:
        print "File doesn't exit. Created a new one. Change location if not running for first time"
        pass
    try:
        num = len(alltasks) + 1
        task = str(num) + " " + task
    except:
        task = '1' + " " + task
        pass
    fl = open(todofile, "a")
    fl.write(task+"\n")
    fl.close()

def delfromtodo(tasknumber):
    tasknumber = int(tasknumber)
    alltasks = []
    try:
        alltasks = open(todofile, "r").readlines()
    except:
        print "Cannot read the todofile"
        exit(1)
    del alltasks[tasknumber-1]
    fl = open(todofile,"w")
    for i in alltasks:
        fl.write(i+'\n')
    fl.close()

def main():
    if len(sys.argv)<2 and len(sys.argv)>4:
        print "Usage: todo <flag:a(add) d(delete)> 'task'"
        print "Usage: todo <flag:l(list) f(flush)>"
    else:
        if sys.argv[1]=='a' and sys.argv[2]:
            addtotodo(sys.argv[2])
        elif sys.argv[1]=='d' and sys.argv[2]:
            delfromtodo(sys.argv[2])
        elif sys.argv[1]=='l':
            try:
                print open(todofile, 'r').read()
            except:
                print "Can't read file"
                exit(1)
        elif sys.argv[1]=='f':
            try:
                open(todofile, 'w').close()
            except:
                print "Cannot flush file"
                exit(1)
        else:
            print "Bad flag!"
            exit(1)

if __name__ == '__main__':
    main()
